name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      IMAGE_NAME_CORE: jobhubportal
      run: |
        echo ${{secrets.REGISTRY_NAME}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install doctl.
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build Container Image
        run: docker build -t registry.digitalocean.com/$REGISTRY_NAME/$IMAGE_NAME_CORE:$(echo $GITHUB_SHA | head -c7) .

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/$REGISTRY_NAME/$IMAGE_NAME_CORE:$(echo $GITHUB_SHA | head -c7)
