name: Angular CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
      DOMAIN_OWNER: ${{ secrets.DOMAIN_OWNER }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      IMAGE_NAME_CORE: angular

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      - name: Log in to AWS CodeArtifact
        run: aws codeartifact login --tool npm --repository $AWS_REPOSITORY --domain $AWS_REPOSITORY --domain-owner $DOMAIN_OWNER

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build Container Image
        run: docker build -t registry.digitalocean.com/$REGISTRY_NAME/$IMAGE_NAME_CORE:$(echo $GITHUB_SHA | head -c7) .

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/$REGISTRY_NAME/$IMAGE_NAME_CORE:$(echo $GITHUB_SHA | head -c7)
